
[firebase_credentials]
type = "service_account"
project_id = "meu-app-final"
private_key_id = "737b73fba85cb3aec953fad2312015d812221bac"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC563QtAShKoVSZ
SSf9d7EaZnmBQ6GmGfdqGUnktXNjg9NbVlQEwxrfqIktZVwUHRQStXT6ELbL7LcN
RHZfGaZO68KBXAVBjBQmSpB1HZCOyKXG6KRNXDML65ZItsk+5TbboFHlP6bG2K8B
sYuMbY0RuaUK5BTbscmLXqwbLBoXq1A+mqvygFB73r+4EzM7zavQUYAu5Ruhs5C/
LPTSyWaPd74jbG+sxuyr5RzcdxOJCER5xo1qoSu6OWXh8ethQhrwPLHTPvDM3QHa
4Sb1JzeKnGM2tC76HHrCAFkfDnRNsVMRF72t1tammdyrGknvsS5hL+j/qGj4ClUj
/CDwuRAPAgMBAAECggEABrNfuoeCJj5uSCAE2vPHZEYxNuFzIANrkV1b9mw7vmhv
46jW2l0VyN3QI9y1Vtw9bvcvQhv8Gplrd4TyJzdLcSi6F+NzJQuhZkflsPLh1OOS
ZfrYgRlDlbhl8DT2R9gHBB9hFDwZDK2ekRcPCn6gSPVB54SU494if21oEoqiXhv0
zIjncP5yc1GqUn2jIyzkAbBGUaHO7TF4UCe6ZJcjb7/KNcwZiUtD55LCskuXY5ro
3h9LVuw93OBwoNucm7C1e9o/8dsRlM6FJP9+xbAfGaOHaZxeyHO/+eII4sXzOTs9
RuglFq5fDFQ7fOR/NwDUUUNUZdACOZ/7Sirvqb72EQKBgQDbmDLozuwHu4hfwsVS
AttPEagQst15kOMX9CiYUbBM6IWvcgCOds4xLF2XwkEuKLARgMv3gK+i72sy+ZNU
3Lp3Z0t+TS4oK1mzYa5EvAy92DHWGxs4UiwxJNzyFaVjqnm/4kfJK+SW1VVeGBtk
48RAx2ovQfMaHb9mouMNdMm49QKBgQDYvhCgCLZgZ3N11aktpw9/XU2+LjJ9+VxW
zS4jPmKUrb/FsBZUYQVkRH9A7HEbcCLS1WlpPJOW+j6JeSSNfTvcREGkqfBUdUgi
hbOq0dOB9cMYJc8ct7Rp86BkkJTaGfRSkidP5KITTfxU1VPa6av43MqH+lvHoXpN
3WphqZrScwKBgQC5BaUneWlwHneKT/6X2iZUmcjkwQBQ9F4TibpGlNWaB3TUXZbQ
cpPK5Nm7C4aF0OyA4ud4k6no/BdzrMuRfiVyg8sdEQSp/dSnis8dxOBreOSMxOwL
aVko0ymCo/BlaHcK0Sqw+tWwrPEvxdoXCL4L4rm6NbQSNixV2zq51MQ+nQKBgFaW
qAGnOWUOLzxWHX5VjYVuew6NWjKlmlQ7KEGAPNX1C/YoQON41zSVgNkpHI6/n8nm
5HPcdYINe0pkkUvNSkrXIfpswcycBjN0grCtnvf+fPB6umFYqsThRaSndjAjyk3q
gbYTOwTHVRV3HEcKr19+pZLpXB1Gz5un50YZAfctAoGBAMZXDkgvEvG/Q0dLGoU5
RkpXNrJm3k2dhagu2mmpwbhduoi3/tPggiROTmMlUgbz4MX/MIBAVKXVf7AfIflr
NZkear9Q6U0OmubVrXtEra/4WLuNNN63K7nWKs3nmSuawf1qNLD7HZi2l+HvWgby
k6/jk6ZHVwcyzMK6CrEe/yDH
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@meu-app-final.iam.gserviceaccount.com"
client_id = "100242932832861566037"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40meu-app-final.iam.gserviceaccount.com"
universe_domain = "googleapis.com"